In [10]:
## Selenium Imports
from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from webdriver_manager.chrome import ChromeDriverManager
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.by import By
import time
import pandas as pd

In [42]:
s = Service("C:\Program Files (x86)\chromedriver.exe") ## get webdriver from localfiles
driver = webdriver.Chrome(service=s) ## instantiate driver

driver.get("https://libertyleagueathletics.com/boxscore.aspx?id=7Gx48kkB20iPlOppZhxXHy%2f5Zy4VtNXkGzuHdKHXRgnKQ3BO%2bJNh1FTebOWr1qPRQbdU5KsUhfYjCyjKhK4HV8YB28RAsIJGjPs3SYmkkNE9DwM9Aq2%2fhj2rWIS2nE02TsrjENP8x0yi%2bnGUcNdMzg%3d%3d&path=mbball") ## get site link for composite schedule

box_score = driver.find_element(by=By.ID, value='box-score')
#print(box_score.get_attribute('outerHTML'))
date = box_score.find_element(by=By.XPATH, value='//*[@id="box-score"]/header/div/div[2]/aside/dl/dd[1]').text
away_team = box_score.find_element(by=By.XPATH, value='//*[@id="box-score"]/header/div/div[1]/table/tbody/tr[1]/th').text
away_score = box_score.find_element(by=By.XPATH, value='//*[@id="box-score"]/header/div/div[1]/table/tbody/tr[1]/td[3]').text
home_team = box_score.find_element(by=By.XPATH, value='//*[@id="box-score"]/header/div/div[1]/table/tbody/tr[2]/th').text
home_score = box_score.find_element(by=By.XPATH, value='//*[@id="box-score"]/header/div/div[1]/table/tbody/tr[2]/td[3]').text

df_list = []

n = 1
for away_player in box_score.find_element(by=By.XPATH, value='//*[@id="DataTables_Table_0"]/tbody').find_elements(by=By.TAG_NAME, value='tr')[0:-1]:
    df_row = {}
    df_row['DATE'] = date
    df_row['AWAY_TEAM'] = away_team
    df_row['AWAY_SCORE'] = away_score
    df_row['HOME_TEAM'] = home_team
    df_row['HOME_SCORE'] = home_score
    df_row['TEAM'] = away_team
    df_row['NUM'] = away_player.find_element(by=By.XPATH, value='./td[1]').text
    df_row['FNAME'] = away_player.find_element(by=By.XPATH, value='./th').text.split(',')[0]
    df_row['LNAME'] = away_player.find_element(by=By.XPATH, value='./th').text.split(',')[1]
    df_row['GS'] = away_player.find_element(by=By.XPATH, value='./td[2]').text
    df_row['MIN'] = away_player.find_element(by=By.XPATH, value='./td[3]').text
    df_row['FGM'] = away_player.find_element(by=By.XPATH, value='./td[4]').text.split('-')[0]
    df_row['FGA'] = away_player.find_element(by=By.XPATH, value='./td[4]').text.split('-')[1]
    df_row['3PTM'] = away_player.find_element(by=By.XPATH, value='./td[5]').text.split('-')[0]
    df_row['3PTA'] = away_player.find_element(by=By.XPATH, value='./td[5]').text.split('-')[1]
    df_row['FTM'] = away_player.find_element(by=By.XPATH, value='./td[6]').text.split('-')[0]
    df_row['FTA'] = away_player.find_element(by=By.XPATH, value='./td[6]').text.split('-')[1]
    df_row['ORB'] = away_player.find_element(by=By.XPATH, value='./td[7]').text.split('-')[0]
    df_row['DRB'] = away_player.find_element(by=By.XPATH, value='./td[7]').text.split('-')[1]
    df_row['TREB'] = away_player.find_element(by=By.XPATH, value='./td[8]').text
    df_row['PF'] = away_player.find_element(by=By.XPATH, value='./td[9]').text
    df_row['A'] = away_player.find_element(by=By.XPATH, value='./td[10]').text
    df_row['TO'] = away_player.find_element(by=By.XPATH, value='./td[11]').text
    df_row['BLK'] = away_player.find_element(by=By.XPATH, value='./td[12]').text
    df_row['STL'] = away_player.find_element(by=By.XPATH, value='./td[13]').text
    df_row['PTS'] = away_player.find_element(by=By.XPATH, value='./td[14]').text

    df_list.append(df_row)

for home_player in box_score.find_element(by=By.XPATH, value='//*[@id="DataTables_Table_1"]/tbody').find_elements(by=By.TAG_NAME, value='tr')[0:-1]:
    df_row = {}
    df_row['DATE'] = date
    df_row['AWAY_TEAM'] = away_team
    df_row['AWAY_SCORE'] = away_score
    df_row['HOME_TEAM'] = home_team
    df_row['HOME_SCORE'] = home_score
    df_row['TEAM'] = home_team
    df_row['NUM'] = home_player.find_element(by=By.XPATH, value='./td[1]').text
    df_row['FNAME'] = home_player.find_element(by=By.XPATH, value='./th').text.split(',')[0]
    df_row['LNAME'] = home_player.find_element(by=By.XPATH, value='./th').text.split(',')[1]
    df_row['GS'] = home_player.find_element(by=By.XPATH, value='./td[2]').text
    df_row['MIN'] = home_player.find_element(by=By.XPATH, value='./td[3]').text
    df_row['FGM'] = home_player.find_element(by=By.XPATH, value='./td[4]').text.split('-')[0]
    df_row['FGA'] = home_player.find_element(by=By.XPATH, value='./td[4]').text.split('-')[1]
    df_row['3PTM'] = home_player.find_element(by=By.XPATH, value='./td[5]').text.split('-')[0]
    df_row['3PTA'] = home_player.find_element(by=By.XPATH, value='./td[5]').text.split('-')[1]
    df_row['FTM'] = home_player.find_element(by=By.XPATH, value='./td[6]').text.split('-')[0]
    df_row['FTA'] = home_player.find_element(by=By.XPATH, value='./td[6]').text.split('-')[1]
    df_row['ORB'] = home_player.find_element(by=By.XPATH, value='./td[7]').text.split('-')[0]
    df_row['DRB'] = home_player.find_element(by=By.XPATH, value='./td[7]').text.split('-')[1]
    df_row['TREB'] = home_player.find_element(by=By.XPATH, value='./td[8]').text
    df_row['PF'] = home_player.find_element(by=By.XPATH, value='./td[9]').text
    df_row['A'] = home_player.find_element(by=By.XPATH, value='./td[10]').text
    df_row['TO'] = home_player.find_element(by=By.XPATH, value='./td[11]').text
    df_row['BLK'] = home_player.find_element(by=By.XPATH, value='./td[12]').text
    df_row['STL'] = home_player.find_element(by=By.XPATH, value='./td[13]').text
    df_row['PTS'] = home_player.find_element(by=By.XPATH, value='./td[14]').text

    df_list.append(df_row)
    
df = pd.DataFrame(df_list)
display(df)

,DATE,AWAY_TEAM,AWAY_SCORE,HOME_TEAM,HOME_SCORE,TEAM,NUM,FNAME,LNAME,GS,...,FTA,ORB,DRB,TREB,PF,A,TO,BLK,STL,PTS
0,12/3/2021,St. Lawrence,51,Union (NY),71,St. Lawrence,33,Engelhardt,Will,*,...,4,1,4,5,2,3,5,0,0,13
1,12/3/2021,St. Lawrence,51,Union (NY),71,St. Lawrence,01,Adamson,Trent,*,...,6,0,1,1,4,0,3,2,1,9
2,12/3/2021,St. Lawrence,51,Union (NY),71,St. Lawrence,03,Davis,Miles,*,...,1,0,1,1,1,0,0,0,0,5
3,12/3/2021,St. Lawrence,51,Union (NY),71,St. Lawrence,02,Syroka,Trey,*,...,2,0,3,3,1,3,1,0,1,4
4,12/3/2021,St. Lawrence,51,Union (NY),71,St. Lawrence,23,Macaulay,Aidan,*,...,4,0,4,4,0,1,0,0,0,4
5,12/3/2021,St. Lawrence,51,Union (NY),71,St. Lawrence,24,Cowan,Andrew,,...,2,0,6,6,1,2,4,2,0,7
6,12/3/2021,St. Lawrence,51,Union (NY),71,St. Lawrence,10,Storey,Carter,,...,0,0,0,0,2,0,0,0,0,6
7,12/3/2021,St. Lawrence,51,Union (NY),71,St. Lawrence,04,Scotnicki,Jack,,...,0,0,0,0,1,0,0,0,0,3
8,12/3/2021,St. Lawrence,51,Union (NY),71,St. Lawrence,13,Macaulay,Gavin,,...,0,1,4,5,0,0,1,0,1,0
9,12/3/2021,St. Lawrence,51,Union (NY),71,St. Lawrence,05,Downs,Andy,,...,0,0,1,1,1,1,1,0,0,0
10,12/3/2021,St. Lawrence,51,Union (NY),71,St. Lawrence,15,McDonald,Liam,,...,0,0,0,0,1,0,0,0,0,0
11,12/3/2021,St. Lawrence,51,Union (NY),71,Union (NY),20,Noone,Brian,*,...,0,1,7,8,1,3,1,0,2,15
12,12/3/2021,St. Lawrence,51,Union (NY),71,Union (NY),03,Manley,Mike,*,...,0,0,5,5,3,6,4,0,1,8
13,12/3/2021,St. Lawrence,51,Union (NY),71,Union (NY),13,George,Temi,*,...,1,2,4,6,4,2,1,0,2,7
14,12/3/2021,St. Lawrence,51,Union (NY),71,Union (NY),11,Regis,Justin,*,...,5,2,3,5,3,4,0,0,1,6
15,12/3/2021,St. Lawrence,51,Union (NY),71,Union (NY),40,Caporale,Mike,*,...,0,2,4,6,2,0,1,0,0,6
16,12/3/2021,St. Lawrence,51,Union (NY),71,Union (NY),22,Baptiste,Edward,,...,2,1,2,3,2,0,1,2,2,16
17,12/3/2021,St. Lawrence,51,Union (NY),71,Union (NY),33,Samsen,Willy,,...,0,2,6,8,4,3,1,1,0,8
18,12/3/2021,St. Lawrence,51,Union (NY),71,Union (NY),14,McGarrity,Luke,,...,0,0,0,0,1,0,1,0,0,3
19,12/3/2021,St. Lawrence,51,Union (NY),71,Union (NY),15,Cepiel,Connor,,...,0,0,0,0,0,1,0,0,0,2
20,12/3/2021,St. Lawrence,51,Union (NY),71,Union (NY),12,Ingoglia,Sean,,...,0,0,0,0,0,2,0,0,0,0
21,12/3/2021,St. Lawrence,51,Union (NY),71,Union (NY),23,Regis,Sean,,...,0,0,0,0,0,0,0,0,0,0

In [3]:
import pandas as pd

player_games_df = pd.read_pickle('./data/historical_boxes.pkl')
display(player_games_df)

,GAME_ID,DATE,AWAY_TEAM,AWAY_SCORE,HOME_TEAM,HOME_SCORE,TEAM,NUM,NAME,GS,...,FTA,ORB,DRB,TREB,PF,A,TO,BLK,STL,PTS
0,0,12/3/2021,St. Lawrence,51,Union (NY),71,St. Lawrence,33,"Engelhardt,Will",*,...,4,1,4,5,2,3,5,0,0,13
1,0,12/3/2021,St. Lawrence,51,Union (NY),71,St. Lawrence,01,"Adamson,Trent",*,...,6,0,1,1,4,0,3,2,1,9
2,0,12/3/2021,St. Lawrence,51,Union (NY),71,St. Lawrence,03,"Davis,Miles",*,...,1,0,1,1,1,0,0,0,0,5
3,0,12/3/2021,St. Lawrence,51,Union (NY),71,St. Lawrence,02,"Syroka,Trey",*,...,2,0,3,3,1,3,1,0,1,4
4,0,12/3/2021,St. Lawrence,51,Union (NY),71,St. Lawrence,23,"Macaulay,Aidan",*,...,4,0,4,4,0,1,0,0,0,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2282,89,2/19/2022,Skidmore,78,Clarkson,66,Clarkson,10,"Rainville,Frankie",,...,0,0,0,0,0,0,0,0,0,0
2283,89,2/19/2022,Skidmore,78,Clarkson,66,Clarkson,11,"Enelamah,Sean",,...,0,0,1,1,0,0,0,0,0,0
2284,89,2/19/2022,Skidmore,78,Clarkson,66,Clarkson,14,"Murphy,Gabe",,...,0,0,0,0,0,0,0,0,0,0
2285,89,2/19/2022,Skidmore,78,Clarkson,66,Clarkson,40,"Cork,Finn",,...,0,0,0,0,0,0,0,0,0,0
2286,89,2/19/2022,Skidmore,78,Clarkson,66,Clarkson,TM,TEAM,,...,0,2,1,3,0,0,0,0,0,0